
#Common config settings
[common]
	#Max level of weapons.
	#Range: > 1
	maxLevel = 25
	#Should weapons remain in inventory on death.
	keepOnDeath = true
	#Base Damage of sword weapons.
	#Range: > 1
	swordDamageMin = 8
	#Max Damage of sword weapons.
	#Range: > 1
	swordDamageMax = 30
	#Base Attack Speed of sword weapons.
	#Range: 0.0 ~ 1.7976931348623157E308
	swordSpeedMin = 1.6
	#Max Attack Speed of sword weapons.
	#Range: 0.0 ~ 1.7976931348623157E308
	swordSpeedMax = 2.4
	#Base Durability of sword weapons.
	#Range: > 1
	swordDurabilityMin = 250
	#Max Durability of sword weapons.
	#Range: > 1
	swordDurabilityMax = 1000
	#Base Damage of rapier weapons.
	#Range: > 1
	rapierDamageMin = 8
	#Max Damage of rapier weapons.
	#Range: > 1
	rapierDamageMax = 26
	#Base Attack Speed of rapier weapons.
	#Range: 0.0 ~ 1.7976931348623157E308
	rapierSpeedMin = 1.8
	#Max Attack Speed of rapier weapons.
	#Range: 0.0 ~ 1.7976931348623157E308
	rapierSpeedMax = 3.5
	#Base Durability of rapier weapons.
	#Range: > 1
	rapierDurabilityMin = 300
	#Max Durability of rapier weapons.
	#Range: > 1
	rapierDurabilityMax = 1200
	#Base Damage of scythe weapons.
	#Range: > 1
	scytheDamageMin = 9
	#Max Damage of scythe weapons.
	#Range: > 1
	scytheDamageMax = 21
	#Base Attack Speed of scythe weapons.
	#Range: 0.0 ~ 1.7976931348623157E308
	scytheSpeedMin = 1.0
	#Max Attack Speed of scythe weapons.
	#Range: 0.0 ~ 1.7976931348623157E308
	scytheSpeedMax = 1.6
	#Base Durability of scythe weapons.
	#Range: > 1
	scytheDurabilityMin = 250
	#Max Durability of scythe weapons.
	#Range: > 1
	scytheDurabilityMax = 900
	#Base Damage of polearm weapons.
	#Range: > 1
	polearmDamageMin = 10
	#Max Damage of polearm weapons.
	#Range: > 1
	polearmDamageMax = 32
	#Base Attack Speed of polearm weapons.
	#Range: 0.0 ~ 1.7976931348623157E308
	polearmSpeedMin = 0.8
	#Max Attack Speed of polearm weapons.
	#Range: 0.0 ~ 1.7976931348623157E308
	polearmSpeedMax = 1.6
	#Base Durability of polearm weapons.
	#Range: > 1
	polearmDurabilityMin = 200
	#Max Durability of polearm weapons.
	#Range: > 1
	polearmDurabilityMax = 900

