
["Cursery settings"]
	#Should enchanted books show a hint for curse magic, default:true
	showDesc = false
	#Add a curse id here to exclude it from beeing applied. To put multiple values seperate them by commas like this:  ["minecraft:curse", "mod:curse;"] 
	excludedCUrses = ["minecraft:vanishing_curse", "minecraft:binding_curse", "cursery:curse_explosive"]
	#Should applying treasure enchants be excluded, default:false
	excludeTreasure = false
	#Base curse application chance, scales up the more enchants the item has. Default:5 %
	#Range: 1 ~ 100
	basecursechance = 3
	#Whether to log debug messages about curse rng beeing rolled, default = false
	debugTries = false
	#Add item which will be not cursed
	excludedItems = ["extraarmor:ender_boots", "extraarmor:cactus_helmet", "extraarmor:obsidian_helmet", "extraarmor:crying_obsidian_helmet", "extraarmor:glowing_obsidian_helmet", "extraarmor:cactus_chestplate", "extraarmor:obsidian_chestplate", "extraarmor:crying_obsidian_chestplate", "extraarmor:glowing_obsidian_chestplate", "extraarmor:cactus_leggings", "extraarmor:obsidian_leggings", "extraarmor:crying_obsidian_leggings", "extraarmor:glowing_obsidian_leggings", "extraarmor:cactus_boots", "extraarmor:obsidian_boots", "extraarmor:crying_obsidian_boots", "extraarmor:glowing_obsidian_boots", "extraarmor:echo_shard_leggings"]
	#Should enchanting success play a sound and show particles, default:true
	visualSuccess = true
	#List of items to disable, they get replaced by air e.g. ["minecraft:elytra"]
	disabledItems = []

